import type { Metadata } from "next";
import ReduxProvider from "@/providers/ReduxProvider";

export const metadata: Metadata = {
  title: "The Next Banking App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="min-h-screenitems-center flex justify-center px-6 py-20">
      <ReduxProvider>{children}</ReduxProvider>
    </div>
  );
}
