import type { Metadata } from "next";
import ReduxProvider from "@/providers/ReduxProvider";
import "./globals.css";

export const metadata: Metadata = {
  title: "The Next Banking App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body>
        <div className="min-h-screenitems-center flex justify-center px-6 py-6 md:py-20">
          <ReduxProvider>{children}</ReduxProvider>
        </div>
      </body>
    </html>
  );
}
